### PR TITLE
Remove Gemfile.lock from Repository 

### PR DESCRIPTION
**Pull request by etagwerker**
Hi there, 

#24 made me think about this: Why are we keeping a Gemfile.lock in this repository? 

I believe the best practice says that you should NOT keep a Gemfile.lock file in the repo of a library?

Anyway, just wondering if we should remove it from the repo. 

Please check it out and let me know.

Thanks!

### CODE REVIEW

**Comment by bronzdoc** [comment]
The practice is to not include a `Gemfile.lock` in a gem but this project is not a gem
https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

**Comment by etagwerker** [comment]
@bronzdoc Is there a good reason to keep a Gemfile.lock in this project's repository? If so, could you please explain?

**Comment by bronzdoc** [comment]
@etagwerker I don't see why we would not need it? It's a regular ruby project with a set of dependencies and we need them to run tests.

**Comment by etagwerker** [comment]
@bronzdoc In my experience it is more of a problem than a helpful thing in the repo. 

More often than not: When I want to make a contribution I run `bundle install` which updates `Gemfile.lock` because there is a new patch version of a dependency or a new version of bundler. Then I have to actively NOT commit that change when I'm about to submit my PR. This is what happened here:

Screen Shot 2021-02-06 at 11 50 31 AM

You ask me why I'm updating Gemfile.lock with that change, I have to go and remove the commit. 

The main reason to have `Gemfile.lock` is to make sure everyone is using the same version of the dependencies in the project when they want to make a contribution. If that is the main reason for keeping it, okay, but I think it is not a good enough reason... 😄 

So, if anything, Gemfile.lock just makes things more complicated.

**Pull request closed without merging**
